### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by wlaurance** [scarvell/flashify#4]
I couldn't get connect-flash to work but your flashify works great!!! Close this 'issue' anytime, just letting you know I'm thankful

**Comment by scarvell** [comment]
No worries, glad it was useful to someone else other than me! 

Do you mind me asking how you came across it? :)

**Comment by bencevans** [comment]
:+1: & Google `Express 3 connect-flash` or something like that

**Comment by wlaurance** [comment]
Pretty much what I googled
